> # Reading the sampled csv dataset into numpy array

In [ ]:
import csv
with open('../data/associationSampleData.csv') as f:
    aprioriArray = list(csv.reader(f, delimiter=";"))
import numpy as np
aprioriArray = np.array(aprioriArray[1:])

In [7]:
aprioriArray

array([['JIO,4G,upload,Gujarat,01/3/19,6,1'],
       ['JIO,4G,upload,Gujarat,01/4/18,5,1'],
       ['AIRTEL,4G,upload,Punjab,01/5/18,2,1'],
       ...,
       ['AIRTEL,4G,download,Maharashtra,01/10/18,3,1'],
       ['JIO,4G,upload,Jammu & Kashmir,01/9/18,4,1'],
       ['VODAFONE,3G,download,Tamil Nadu,01/12/18,4,1']], dtype='<U50')

> # using mlxtend library for association analysis

In [8]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [9]:
te = TransactionEncoder()
te_ary = te.fit(aprioriArray).transform(aprioriArray)
te_ary

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [10]:
oht = TransactionEncoder()
oht_ary = oht.fit(aprioriArray).transform(aprioriArray)
df2 = pd.DataFrame(oht_ary, columns=oht.columns_)
print (df2)

        AIRTEL,2G,download,UP West,01/4/18,7,1  \
0                                        False
1                                        False
2                                        False
3                                        False
4                                        False
...                                        ...
126487                                   False
126488                                   False
126489                                   False
126490                                   False
126491                                   False

        AIRTEL,2G,upload,West Bengal,01/4/18,5,1  \
0                                          False
1                                          False
2                                          False
3                                          False
4                                          False
...                                          ...
126487                                     False
126488                                     False
126489                                     False
126490                                     False
126491                                     False

        AIRTEL,3G,download,Andhra Pradesh,01/1/19,3,1  \
0                                               False
1                                               False
2                                               False
3                                               False
4                                               False
...                                               ...
126487                                          False
126488                                          False
126489                                          False
126490                                          False
126491                                          False

        AIRTEL,3G,download,Andhra Pradesh,01/1/19,4,1  \
0                                               False
1                                               False
2                                               False
3                                               False
4                                               False
...                                               ...
126487                                          False
126488                                          False
126489                                          False
126490                                          False
126491                                          False

        AIRTEL,3G,download,Andhra Pradesh,01/10/18,3,1  \
0                                                False
1                                                False
2                                                False
3                                                False
4                                                False
...                                                ...
126487                                           False
126488                                           False
126489                                           False
126490                                           False
126491                                           False

        AIRTEL,3G,download,Andhra Pradesh,01/10/18,4,1  \
0                                                False
1                                                False
2                                                False
3                                                False
4                                                False
...                                                ...
126487                                           False
126488                                           False
126489                                           False
126490                                           False
126491                                           False

        AIRTEL,3G,download,Andhra Pradesh,01/10/18,6,1  \
0                                                False
1                                                False
2                                                False
3                                                False
4                                                False
...                                                ...
126487                                           False
126488                                           False
126489                                           False
126490                                           False
126491                                           False

        AIRTEL,3G,download,Andhra Pradesh,01/11/18,2,1  \
0                                                False
1                                                False
2                                                False
3                                                False
4                                                False
...                                                ...
126487                                           False
126488                                           False
126489                                           False
126490                                           False
126491                                           False

        AIRTEL,3G,download,Andhra Pradesh,01/11/18,3,1  \
0                                                False
1                                                False
2                                                False
3                                                False
4                                                False
...                                                ...
126487                                           False
126488                                           False
126489                                           False
126490                                           False
126491                                           False

        AIRTEL,3G,download,Andhra Pradesh,01/11/18,4,1  ...  \
0                                                False  ...
1                                                False  ...
2                                                False  ...
3                                                False  ...
4                                                False  ...
...                                                ...  ...
126487                                           False  ...
126488                                           False  ...
126489                                           False  ...
126490                                           False  ...
126491                                           False  ...

        VODAFONE,4G,upload,West Bengal,01/7/19,4,3  \
0                                            False
1                                            False
2                                            False
3                                            False
4                                            False
...                                            ...
126487                                       False
126488                                       False
126489                                       False
126490                                       False
126491                                       False

        VODAFONE,4G,upload,West Bengal,01/7/19,5,1  \
0                                            False
1                                            False
2                                            False
3                                            False
4                                            False
...                                            ...
126487                                       False
126488                                       False
126489                                       False
126490                                       False
126491                                       False

        VODAFONE,4G,upload,West Bengal,01/8/18,2,1  \
0                                            False
1                                            False
2                                            False
3                                            False
4                                            False
...                                            ...
126487                                       False
126488                                       False
126489                                       False
126490                                       False
126491                                       False

        VODAFONE,4G,upload,West Bengal,01/8/18,3,1  \
0                                            False
1                                            False
2                                            False
3                                            False
4                                            False
...                                            ...
126487                                       False
126488                                       False
126489                                       False
126490                                       False
126491                                       False

        VODAFONE,4G,upload,West Bengal,01/8/18,4,1  \
0                                            False
1                                            False
2                                            False
3                                            False
4                                            False
...                                            ...
126487                                       False
126488                                       False
126489                                       False
126490                                       False
126491                                       False

        VODAFONE,4G,upload,West Bengal,01/8/18,4,2  \
0                                            False
1                                            False
2                                            False
3                                            False
4                                            False
...                                            ...
126487                                       False
126488                                       False
126489                                       False
126490                                       False
126491                                       False

        VODAFONE,4G,upload,West Bengal,01/9/18,2,1  \
0                                            False
1                                            False
2                                            False
3                                            False
4                                            False
...                                            ...
126487                                       False
126488                                       False
126489                                       False
126490                                       False
126491                                       False

        VODAFONE,4G,upload,West Bengal,01/9/18,3,1  \
0                                            False
1                                            False
2                                            False
3                                            False
4                                            False
...                                            ...
126487                                       False
126488                                       False
126489                                       False
126490                                       False
126491                                       False

        VODAFONE,4G,upload,West Bengal,01/9/18,4,1  \
0                                            False
1                                            False
2                                            False
3                                            False
4                                            False
...                                            ...
126487                                       False
126488                                       False
126489                                       False
126490                                       False
126491                                       False

        VODAFONE,4G,upload,West Bengal,01/9/18,4,2
0                                            False
1                                            False
2                                            False
3                                            False
4                                            False
...                                            ...
126487                                       False
126488                                       False
126489                                       False
126490                                       False
126491                                       False

[126492 rows x 22209 columns]

> # Frequent itemsets from apriori with minimum support

In [11]:
frequent_itemsets = apriori(df2, min_support=0.0005, use_colnames=True)
print (frequent_itemsets)

      support                                      itemsets
0    0.000506      (AIRTEL,4G,download,UP East,01/7/18,4,1)
1    0.000538        (AIRTEL,4G,upload,UP East,01/4/18,4,1)
2    0.000577        (AIRTEL,4G,upload,UP East,01/7/18,4,1)
3    0.001028  (JIO,4G,download,Andhra Pradesh,01/4/18,3,1)
4    0.000672  (JIO,4G,download,Andhra Pradesh,01/5/18,3,1)
..        ...                                           ...
144  0.001028           (JIO,4G,upload,UP West,01/4/18,6,1)
145  0.000688           (JIO,4G,upload,UP West,01/5/18,3,1)
146  0.000569           (JIO,4G,upload,UP West,01/5/18,5,1)
147  0.000830           (JIO,4G,upload,UP West,01/7/18,5,1)
148  0.000743       (JIO,4G,upload,West Bengal,01/5/18,5,1)

[149 rows x 2 columns]

> # Possible association rules with min confidence

In [12]:
from mlxtend.frequent_patterns import association_rules

association_rules(frequent_itemsets , metric="confidence", min_threshold=0)

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction]
Index: []

> # dataframe for fpgrowth

In [13]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(aprioriArray).transform(aprioriArray)
df3 = pd.DataFrame(te_ary, columns=te.columns_)
df3

,"AIRTEL,2G,download,UP West,01/4/18,7,1","AIRTEL,2G,upload,West Bengal,01/4/18,5,1","AIRTEL,3G,download,Andhra Pradesh,01/1/19,3,1","AIRTEL,3G,download,Andhra Pradesh,01/1/19,4,1","AIRTEL,3G,download,Andhra Pradesh,01/10/18,3,1","AIRTEL,3G,download,Andhra Pradesh,01/10/18,4,1","AIRTEL,3G,download,Andhra Pradesh,01/10/18,6,1","AIRTEL,3G,download,Andhra Pradesh,01/11/18,2,1","AIRTEL,3G,download,Andhra Pradesh,01/11/18,3,1","AIRTEL,3G,download,Andhra Pradesh,01/11/18,4,1",...,"VODAFONE,4G,upload,West Bengal,01/7/19,4,3","VODAFONE,4G,upload,West Bengal,01/7/19,5,1","VODAFONE,4G,upload,West Bengal,01/8/18,2,1","VODAFONE,4G,upload,West Bengal,01/8/18,3,1","VODAFONE,4G,upload,West Bengal,01/8/18,4,1","VODAFONE,4G,upload,West Bengal,01/8/18,4,2","VODAFONE,4G,upload,West Bengal,01/9/18,2,1","VODAFONE,4G,upload,West Bengal,01/9/18,3,1","VODAFONE,4G,upload,West Bengal,01/9/18,4,1","VODAFONE,4G,upload,West Bengal,01/9/18,4,2"
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126487,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
126488,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
126489,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
126490,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
126491,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

> # Frequent itemsets from fpgrowth with minimum support

In [14]:
from mlxtend.frequent_patterns import fpgrowth

fpgrowth(df3, min_support=0.0005)

      support itemsets
0    0.000719  (16615)
1    0.001083  (16613)
2    0.000569  (18286)
3    0.000656  (16366)
4    0.002119  (16368)
..        ...      ...
144  0.000688  (18284)
145  0.000609  (17288)
146  0.000514  (18187)
147  0.000553  (11683)
148  0.000609  (13494)

[149 rows x 2 columns]

In [15]:
fpgrowth(df3, min_support=0.0005, use_colnames=True)

      support                                    itemsets
0    0.000719         (JIO,4G,upload,Gujarat,01/4/18,5,1)
1    0.001083         (JIO,4G,upload,Gujarat,01/4/18,3,1)
2    0.000569         (JIO,4G,upload,UP West,01/5/18,5,1)
3    0.000656           (JIO,4G,upload,Bihar,01/6/18,6,1)
4    0.002119           (JIO,4G,upload,Bihar,01/6/18,8,1)
..        ...                                         ...
144  0.000688         (JIO,4G,upload,UP West,01/5/18,3,1)
145  0.000609  (JIO,4G,upload,Madhya Pradesh,01/6/18,7,1)
146  0.000514         (JIO,4G,upload,UP East,01/6/18,8,1)
147  0.000553       (JIO,4G,download,Gujarat,01/7/18,3,1)
148  0.000609   (JIO,4G,download,Maharashtra,01/2/19,3,1)

[149 rows x 2 columns]